### PR TITLE
Reswitch to OASIS

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Does someone wants to take care of it ?

**Comment by Drup** [comment]
I'm (obviously) in favor of this, but I'm gonna wait for other people's opinion. @shakurra, @balat ?

**Comment by ccharly** [comment]
I think that we should wait the @balat's opinion before merging it.

IMO, I prefer Makefile because it's easier to add some specific rules (and because I don't really know OASIS too).

So, let's wait @balat. :)

**Comment by kit-ty-kate** [comment]
ping

**Comment by Drup** [comment]
Since @jpdeplaix asked for it : this changes have my approval. :]

**Pull request merged**
